language: node_js
node_js:
  - 8.12.0
sudo: required
env:
  global:
    - CXX=g++-4.8
  matrix:
    - USE_SENTRY=0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm install
  - npm run build:dll
  - npm run build

before_deploy:
  - find dist/ -type f -name "*.map" -delete
  - zip -r dist.zip dist
  - git config --local user.name "Gumbeat"
  - git config --local user.email "leo2598@yandex.ua"
  - git tag latest

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: $GITHUB_TOKEN
  file: dist.zip
  on:
    repo: Gumbeat/OnlineJudgeFE
    all_branches: true
    tags: false
