language: node_js
node_js:
  - 6.11.2
sudo: required
services:
  - docker
env:
  global:
    - CXX=g++-4.8
  matrix:
    - USE_SENTRY=0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm install
  - npm run build:dll
  - npm run build

before_deploy:
  - bash deploy/sentry_release.sh
  - find dist/ -type f -name "*.map" -delete
  - zip -r dist.zip dist

deploy:
  provider: releases
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  file: dist.zip
  on:
    repo: Gumbeat/OnlineJudgeFE
    all_branches: true
    tags: false
